// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLISo4FBtnXNLPSHbfQQh3eTfuqzAiDAg',
    appId: '1:175238473511:web:2b58f4321f0dd98c2c2b02',
    messagingSenderId: '175238473511',
    projectId: 'daurulangsampah-e5107',
    authDomain: 'daurulangsampah-e5107.firebaseapp.com',
    storageBucket: 'daurulangsampah-e5107.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM1vf_tL6ufEVEa1HBh41DHtGcAdTdvqg',
    appId: '1:175238473511:android:30b5a959c412b2592c2b02',
    messagingSenderId: '175238473511',
    projectId: 'daurulangsampah-e5107',
    storageBucket: 'daurulangsampah-e5107.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnTkLTWywjYGvLdwAaaSX5u4IK_YZqJxc',
    appId: '1:175238473511:ios:fc930ee8a5a2f1162c2b02',
    messagingSenderId: '175238473511',
    projectId: 'daurulangsampah-e5107',
    storageBucket: 'daurulangsampah-e5107.appspot.com',
    iosClientId: '175238473511-csed1u6fjvjn5j6nrn54u3it96fo6jod.apps.googleusercontent.com',
    iosBundleId: 'com.example.dusApp',
  );
}
